In [1]:
import numpy as np

np.__version__

'2.3.3'

## Creating Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5) # this is to specify creating an array with different elements
# the first argument is the size of the array and the second argument is the value to fill the array with

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 3, 5, 7, 12])
a

array([ 1,  3,  5,  7, 12])

In [6]:
a[2]

np.int64(5)

In [7]:
a[1] = 10
a

array([ 1, 10,  5,  7, 12])

In [8]:
np.arange(10) # creates a range of arrays from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 5) # creates an array of 5 elements between 0 and 1 (inclusive)

array([  0.,  25.,  50.,  75., 100.])

## Multi-dimensional Arrays

In [12]:
np.zeros((5, 2)) # creates a 2D array with 5 rows and 2 columns filled with zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [15]:
n[0, 1] # row, column

np.int64(2)

In [16]:
n[0, 1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[0] # get the entire row

array([ 1, 20,  3])

In [19]:
n[2] = [4, 8, 16]

In [20]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 4,  8, 16]])

In [ ]:
n[:, 1] # get all the rows but keep the second column

array([20,  5,  8])

In [22]:
n[:, 2] = [9, 18, 27]
n

array([[ 1, 20,  9],
       [ 4,  5, 18],
       [ 4,  8, 27]])

## Randomly generated arrays

In [30]:
np.random.seed(2) # to make the random numbers predictable
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
np.random.randn(5, 2) # generates random numbers from a normal distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [32]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]])

## Element-wise operators

In [35]:
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [34]:
b + 1

array([1, 2, 3, 4, 5, 6])

In [36]:
b * 2

array([ 0,  2,  4,  6,  8, 10])

In [39]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [40]:
b ** 2 * (a + b)

array([  0,   2,  16,  54, 128, 250])

In [41]:
a + b

array([ 0,  2,  4,  6,  8, 10])

## Comparison Operators

In [42]:
a > b

array([False, False, False, False, False, False])

In [43]:
a < b

array([False, False, False, False, False, False])

In [44]:
a == b

array([ True,  True,  True,  True,  True,  True])

In [45]:
a >= 2

array([False, False,  True,  True,  True,  True])

In [46]:
b <= 4

array([ True,  True,  True,  True,  True, False])

In [ ]:
a[a <= b] # boolean indexing

array([0, 1, 2, 3, 4, 5])

## Summarizing operations

In [49]:
a.min()

np.int64(0)

In [50]:
a.max()

np.int64(5)

In [51]:
a.sum()

np.int64(15)

In [52]:
b.mean()

np.float64(2.5)

In [53]:
a.std()

np.float64(1.707825127659933)

In [54]:
b.std()

np.float64(1.707825127659933)

In [55]:
n.mean()

np.float64(10.666666666666666)

In [56]:
n.sum()

np.int64(96)

In [57]:
n.min()

np.int64(1)

In [58]:
n.max()

np.int64(27)

In [59]:
n.std()

np.float64(8.379870059984357)