In [1]:
# Vector Operations
import numpy as np

def add_vectors(v1, v2):
    """add two vectors"""
    return np.add(v1, v2)

def multiply_vector_scalar(v, s):
    """multiply vector by scalar"""
    return np.multiply(v, s)

def dot_product(v1, v2):
    """compute dot product of two vectors"""
    assert v1.shape[0] == v2.shape[0], "Vectors must be of same length"
    
    return np.dot(v1, v2) # vector-vector multiplication
"""
For dot product, each element of one vector is multiplied by the corresponding element of the other vector
the results are then summed to produce a single scalar value.
"""

'\nFor dot product, each element of one vector is multiplied by the corresponding element of the other vector\nthe results are then summed to produce a single scalar value.\n'

In [2]:
"""
To convert a column vector to a row vector, you have to use the transpose function
v = np.array([[1], [2], [3]])  # Column vector
v_row = v.T  # Transpose to get row vector"""
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
dot_product_result = dot_product(v1,v2)
print("Dot Product:", dot_product_result)

Dot Product: 32


In [3]:
# Matrix vector multiplication
'''
You multiply each row of the matrix by the vector
Both should have equal n number of elements
'''
mat_u = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

vect_v = np.array([1, 0.5, 2, 1])
print(f'{mat_u}\n{vect_v}')

[[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]
[1.  0.5 2.  1. ]


In [4]:
def matrix_vector_multiplication(mat, vec):
    assert mat.shape[1] == vec.shape[0], "matrix columns must equal vector length"
    
    num_rows = mat.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = dot_product(mat[i], vec)
        
    return result

In [5]:
vector_result = matrix_vector_multiplication(mat_u, vect_v)
print("Matrix-Vector Multiplication Result:", vector_result)


Matrix-Vector Multiplication Result: [20.   6.   8.5]


In [6]:
'''
numpy formula will be result = np.dot(mat, vec)
'''

'\nnumpy formula will be result = np.dot(mat, vec)\n'

In [7]:
# Matrix-matrix operations
"""
To multiply two matrices, the number of columns in the first matrix must equal the number of rows in the second matrix.
"""
def matrix_matrix_multiplication(mat_a, mat_b):
    assert mat_a.shape[1] == mat_b.shape[0], "First matrix columns must equal second matrix rows"
    
    num_rows_a = mat_a.shape[0]
    num_cols_b = mat_b.shape[1]
    
    result = np.zeros((num_rows_a, num_cols_b))
    
    for i in range(num_rows_a):
        for j in range(num_cols_b):
            result[i, j] = dot_product(mat_a[i], mat_b[:, j])
    
    return result

In [10]:
mat_v = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [3, 0, 5, 9],
    [1, 0, 2, 1]
])

In [11]:
matrix_matrix_multiplication(mat_u, mat_v)

array([[43., 28., 71., 91.],
       [16., 14., 26., 31.],
       [15., 12., 28., 39.]])

In [12]:
np.dot(mat_u, mat_v)

array([[43, 28, 71, 91],
       [16, 14, 26, 31],
       [15, 12, 28, 39]])

In [14]:
# Identity Matrix
"""
An identity matrix is a square matrix in which all the elements of the principal diagonal are ones, and all other elements are zeros.
When you multiply any matrix by an identity matrix of compatible dimensions, the original matrix remains unchanged.
"""
I = np.eye(3)

In [16]:
v1.dot(I)

array([1., 2., 3.])

In [22]:
# Matrix inverse
"""
An inverse of a matrix is a matrix that, when multiplied with the original matrix, results in an identity matrix.
The inverse of a matrix A is denoted as A^(-1), and it exists only for square matrices that are non-singular (i.e., they have a non-zero determinant).
"""
U = mat_u[[0, 1, 2]]
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [23]:
# Check the shape of U
print("Shape of U:", U.shape)
print("U is a 3x4 matrix, but inverse only works for square matrices!")
print("\nLet's create a square matrix for the inverse example:")

# Create a 3x3 square matrix from the first 3 columns of U
U_square = U[:, :3]  # Take first 3 columns
print("Shape of U_square:", U_square.shape)
print("U_square:\n", U_square)

Shape of U: (3, 4)
U is a 3x4 matrix, but inverse only works for square matrices!

Let's create a square matrix for the inverse example:
Shape of U_square: (3, 3)
U_square:
 [[2 4 5]
 [1 2 1]
 [3 1 2]]


In [24]:
# Compute the inverse of the square matrix
Uinv = np.linalg.inv(U_square)
print("Inverse of U_square:")
print(Uinv)

Inverse of U_square:
[[-0.2         0.2         0.4       ]
 [-0.06666667  0.73333333 -0.2       ]
 [ 0.33333333 -0.66666667 -0.        ]]


In [25]:
# Verify the inverse by multiplying U_square with its inverse
# This should give us the identity matrix
identity_check = np.dot(U_square, Uinv)
print("U_square × U_inverse (should be identity matrix):")
print(identity_check)
print("\nRounded to remove floating point errors:")
print(np.round(identity_check, 10))

U_square × U_inverse (should be identity matrix):
[[ 1.00000000e+00  3.33066907e-16  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Rounded to remove floating point errors:
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
