In [11]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.2'

## Retrieve the data

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-24 21:13:35--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.1’

car_fuel_efficiency 100%[===================>] 853.70K  66.3KB/s    in 22s     

2025-09-24 21:14:00 (38.7 KB/s) - ‘car_fuel_efficiency.csv.1’ saved [874188/874188]



In [12]:
# load the data
cfd = pd.read_csv('car_fuel_efficiency.csv')

# print the first 5 rows
cfd.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Records count

In [5]:
#  get shape of the dataframe
cfd.shape # there are 9704 records in the dataset

(9704, 11)

## Fuel types

In [6]:
cfd['fuel_type'].value_counts() # there are two fuel types

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

## Missing values

In [7]:
count = 0
for col in cfd.columns:
    num_missing_cols = cfd.isna().sum()[col]
    if num_missing_cols > 0:
        count += 1
print(f"Total columns with missing_values: {count}\nMissing cols are: {cfd.columns[cfd.isna().sum() > 0].tolist()}")

Total columns with missing_values: 4
Missing cols are: ['num_cylinders', 'horsepower', 'acceleration', 'num_doors']


## Max fuel efficiency 

In [8]:
cfd['fuel_efficiency_mpg'].max()

np.float64(25.96722204888372)

In [9]:
cfd['origin'] == 'Asia'

0       False
1       False
2       False
3       False
4       False
        ...  
9699    False
9700    False
9701    False
9702    False
9703     True
Name: origin, Length: 9704, dtype: bool

In [15]:
max_fuel_efficiency_asia = cfd[cfd['origin'] == 'Asia']['fuel_efficiency_mpg'].max()
print(f"Max fuel efficiency for cars from Asia: {max_fuel_efficiency_asia} mpg")

Max fuel efficiency for cars from Asia: 23.759122836520497 mpg


## Median value of horsepower

In [18]:
# median value of horsepower
horsepower_median = cfd.horsepower.median()

# mode of horsepower
horsepower_mode = cfd.horsepower.mode()[0]

print(f"Median horsepower value: {horsepower_median}\nMost frequent value on horsepower column: {horsepower_mode}")

Median horsepower value: 149.0
Most frequent value on horsepower column: 152.0


In [19]:
# fill missing values in horsepower column with mode
cfd['horsepower'] = cfd['horsepower'].fillna(horsepower_mode)

In [ ]:
# recalculate median
median_hp_new = cfd.horsepower.median()
median_hp_newn # median increased after imputing missing values with mode

np.float64(152.0)

## Sum of weights

In [21]:
# Asia cars dataframe
asia_cars = cfd[cfd['origin'] == 'Asia']
asia_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [22]:
select_cols = asia_cars[['vehicle_weight', 'model_year']]
select_cols

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [24]:
# select the first 7 values
first_seven = select_cols.iloc[:7]
first_seven

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [26]:
# get underlying numpy array
X = first_seven.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [27]:
# matrix-matrix multiplication
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [28]:
# invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [31]:
inv_trans = XTX_inv.dot(X.T)
w = inv_trans.dot(y)
w

array([0.01386421, 0.5049067 ])

In [32]:
w_sum= sum(w)
w_sum

np.float64(0.5187709081074016)